name: Check PR Title

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR title for Git Flow format
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"
          if [[ ! "$PR_TITLE" =~ ^(feature|hotfix|release)/ ]]; then
            echo "❌ PR title must start with 'feature/', 'hotfix/', or 'release/'"
            exit 1
          fi
          echo "✅ PR title is valid"
